### ISSUE TITLE
Allow setting a default value for auto-tangle

### ISSUE THREAD

**Issue by zzamboni** [yilkalargaw/org-auto-tangle#4]
First of all, **THANK YOU** for this package. I've been using tangle-on-save using a manually configured hook for a long time, but I had been wishing for an easy way to do this asynchronously. `org-auto-tangle` works beautifully.

Most of my Org files include code that needs to be tangled, so I was wondering if it would be possible to add a variable to set the default behavior to auto-tangle. This would make it easier to use `org-auto-tangle` without having to modify all my existing Org files :)

(I'll put together a PR if/when I have some time, but in the meantime thought it wouldn't hurt to ask for it).

**Comment by yilkalargaw** [comment]
It was solved by your[ pull request ](https://github.com/yilkalargaw/org-auto-tangle/pull/5) thanks.
