### ISSUE TITLE
Doesn't work with sudo tramp tangle file due to async-ness

### ISSUE THREAD

**Issue by indigoviolet** [yilkalargaw/org-auto-tangle#9]
```
#+begin_src shell :tangle "/sudo::/tmp/foo"
test test
#+end_src
```
Consider a `test.org` that looks like above.

`org-auto-tangle` will not tangle this -- a password buffer named `*emacs*` will be created and hang around. 

`org-babel-tangle` will create a file named `/tmp/foo` owned by root.

I realize this might not be an easy bug to resolve due to the async nature of org-auto-tangle, but I think the silent failure/skipping of blocks is not good: if the async call doesn't terminate successfully in some time, we should throw an error?

**Comment by indigoviolet** [comment]
@yilkalargaw

1) This still skips blocks - there is only a message in the minibuffer
2) With the right `auth-sources` setup (https://www.gnu.org/software/emacs/manual/html_mono/auth.html), `org-babel-tangle` will decrypt your password from some encrypted file and use it to create the root-owned `/tmp/foo`, without any user interaction (after we've given emacs the password to decrypt the gpg file one time). 
Should auto-tangle be able to do this?

**Comment by indigoviolet** [comment]
Would it make sense to have a configuration flag to fall through to `org-babel-tangle` on save (synchronously) for some buffers, to handle such cases?

**Comment by yilkalargaw** [comment]
I'm currently looking to add some way of logging failure from the async session so that it could be caught with an exception and  fail to org-babel-tangle. I'll look into the config flag but can't a user simply use file-find-hook to disable autotangling for now? 
```elisp
(add-hook 'find-file-hook
          (lambda ()
            (when (file-remote-p default-directory)
                 (org-auto-tangle-mode nil))))
```
I've not tried it so let me know.

ps. Sorry for the slow responses I was not able to work on it for the past few months but I'll be able to work on them within a few weeks. It would be nice to iron out some of the issues.

**Comment by indigoviolet** [comment]
Thanks for the response @yilkalargaw . If you see my example above, https://github.com/yilkalargaw/org-auto-tangle/issues/9#issue-915611219, it's not (I think) a per-file thing, but a per-block thing: I often have literate configs that will write to root-owned files and non-root-owned files, and the `:tangle` header config selects the target by setting it up as `/sudo::`. Will the hook you suggested work in that situation? 

>With the right auth-sources setup (https://www.gnu.org/software/emacs/manual/html_mono/auth.html), org-babel-tangle will decrypt your password from some encrypted file and use it to create the root-owned /tmp/foo, without any user interaction (after we've given emacs the password to decrypt the gpg file one time).
Should auto-tangle be able to do this?

**Comment by gowallasnewpony** [comment]
> I'm currently looking to add some way of logging failure from the async session so that it could be caught with an exception and fail to org-babel-tangle. I'll look into the config flag but can't a user simply use file-find-hook to disable autotangling for now?
> 
> ```emacs-lisp
> (add-hook 'find-file-hook
>           (lambda ()
>             (when (file-remote-p default-directory)
>                  (org-auto-tangle-mode nil))))
> ```
> 
> I've not tried it so let me know.
> 
> ps. Sorry for the slow responses for issues I was not able to work on this project for the past few months but I'll be able to work on it within a few weeks. It would be nice to iron out some of the issues.

This didn't seem to work in my case ...
